# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - dfberry-temp-nest-swagger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          cd nest-openapi
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-nestjs-openapi
          path: |
            ./nest-openapi
            !./nest-openapi/node_modules

  # configapp: 
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:

  #     # Learn more: https://github.com/marketplace/actions/azure-cli-action#configure-azure-credentials-as-github-secret

  #     - name: Login via Azure CLI
  #       uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }} # Define secret variable in repository settings as per action documentation

  #     - name: 'Configure Azure App Service'
  #       uses: azure/CLI@v1
  #       with:
  #         inlineScript: |
  #           az webapp config appsettings set -g dfberry-enterprise-temp -n dfberry-temp-nest-swagger --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true


  deploy:
    runs-on: ubuntu-latest
    #needs: configapp
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-nestjs-openapi

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dfberry-temp-nest-swagger'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_707F50DAE9A34AE683DAD29534C9FB92 }}
          package: .
